version: "3.8"

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://kong:kong_password@db:5432/kong_db?sslmode=disable
      - PORT=8080
    depends_on:
      - db
    command: ./main

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kong_password
      - POSTGRES_DB=kong_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/scripts

volumes:
  postgres_data:
